// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qefedibmzskwffozmryc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlZmVkaWJtenNrd2Zmb3ptcnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Njc1NDgsImV4cCI6MjA1ODQ0MzU0OH0.vWPo36bCNoCwwuweDUpuoPdLWfQQ5UwF9qTCrhQ4ZJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);